-- Create a dedicated table for New User Applications
create table if not exists new_applications (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references users(id) on delete cascade,
  first_name text,
  last_name text,
  email text,
  phone text,
  status text default 'pending'
);

-- Note: The `settings` table operates as a Key-Value Store for metadata.
create table if not exists settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value text,
  updated_at timestamp with time zone default now()
);

-- Messages Table
create table if not exists messages (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references users(id) on delete cascade,
  subject text not null,
  body text not null,
  is_read boolean default false
);

-- Statements Table
create table if not exists statements (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references users(id) on delete cascade,
  title text not null,
  date text not null, -- Display string for period (e.g. "Dec 2025")
  pdf_url text
);

-- Enable RLS
alter table new_applications enable row level security;
alter table messages enable row level security;
alter table statements enable row level security;

-- Policies (Permissive for simulation demo)
create policy "Allow all operations new_apps" on new_applications for all using (true) with check (true);
create policy "Allow all operations messages" on messages for all using (true) with check (true);
create policy "Allow all operations statements" on statements for all using (true) with check (true);

-- Transactions table (Ensure RLS is enabled and permissive)
alter table transactions enable row level security;
create policy "Allow all operations transactions" on transactions for all using (true) with check (true);
