// --- Supabase Config ---
const SUPABASE_URL = 'https://igwvqcwwrrrwunsgykxk.supabase.co';
const SUPABASE_KEY = 'sb_publishable_KCtVujwVKyQsw4vVrWrMFw_j-eZOKzP'; // User provided key

// Initialize Client (Relies on CDN script being loaded in HTML)
let supabaseClient = null;

const utils = {
    init: () => {
        if (window.supabase) {
            const { createClient } = window.supabase;
            supabaseClient = createClient(SUPABASE_URL, SUPABASE_KEY);
            console.log('Supabase Connected');
        } else {
            console.error('Supabase SDK not loaded');
        }
        // Apply cached branding immediately
        utils.applyBranding();
        // Then fetch fresh
        utils.getBranding();
    },

    // --- System Branding ---
    brandingDefaults: {
        bankName: 'Orion',
        primaryColor: '#002855', // Deep Navy Blue
        metaUrl: 'meta.png'
    },

    saveBranding: async (settings) => {
        // 1. Update Cache Immediately (Optimistic)
        const current = utils.getBrandingCache();
        const newConfig = { ...current, ...settings };
        localStorage.setItem('branding', JSON.stringify(newConfig));
        utils.applyBranding();

        // 2. Try to persist to DB
        // settings: { bank_name, primary_color }
        // We will store as rows: { key: 'bank_name', value: '...' }
        const upserts = Object.keys(settings).map(key => ({
            key: key,
            value: settings[key]
        }));

        const { error } = await supabaseClient
            .from('settings')
            .upsert(upserts, { onConflict: 'key' });

        if (error) {
            console.error("DB Save Failed (using local cache)", error);
            // We don't throw here to avoid showing a scary error to the user if the local update worked.
            // Or we can throw but arguably if the local part worked, the user is happy for now.
            // Let's rely on the Admin Check catch block to warn if needed, but for "Remove Node/Local" use case, silencing is better.
            if (error.message && error.message.includes("relation")) throw error; // Re-throw critical table errors
        }
    },

    getBranding: async () => {
        const { data, error } = await supabaseClient
            .from('settings')
            .select('*');

        if (error) {
            console.error('Failed to fetch branding:', error);
            // On error, prefer cache to prevent flashing defaults
            return utils.getBrandingCache();
        }

        // If DB is empty, trust local cache if it has custom values (User saved but DB failed/empty)
        if (!data || data.length === 0) {
            const cached = utils.getBrandingCache();
            // If cache differs from defaults, assume it's valid user input awaiting sync
            if (cached.bankName !== utils.brandingDefaults.bankName || cached.primaryColor !== utils.brandingDefaults.primaryColor) {
                return cached;
            }
            return utils.brandingDefaults;
        }

        // Convert rows to object
        const dbConfig = {};
        if (data && data.length > 0) {
            data.forEach(row => dbConfig[row.key] = row.value);
        }

        // Global Sync Strategy:
        // 1. Defaults
        // 2. Cache (Local Fallback)
        // 3. DB (Global Truth) - Apply LAST to ensure all users see the same latest data

        // If DB is empty/failed (dbConfig has no keys), we naturally fall back to Cache.
        const cached = utils.getBrandingCache();
        const final = { ...utils.brandingDefaults, ...cached, ...dbConfig };

        localStorage.setItem('branding', JSON.stringify(final));
        utils.applyBranding();
        return final;
    },

    getBrandingCache: () => {
        const cached = localStorage.getItem('branding');
        return cached ? JSON.parse(cached) : utils.brandingDefaults;
    },

    applyBranding: () => {
        const config = utils.getBrandingCache();

        // 1. CSS Variables
        if (config.primaryColor) {
            // Tailwind doesn't support dynamic var updates easily unless we use CSS var
            // Luckily we extended tailwind config in HTML to use colors: { "primary": "#..." }? 
            // No, the HTML config is static JS object. 
            // We need to inject a style tag or override variable.
            // Our index.html says: colors: { "primary": "#0033cc" }
            // We can't change that at runtime easily without rebuilding config.
            // BUT, we can override the CSS classes if we used CSS variables.
            // Wait, the HTML uses `bg-primary` which is generated by Tailwind CDN.
            // We can override the color by setting `tailwind.config.theme.extend.colors.primary = ...` AND re-running? 
            // No, CDN runs once.

            // Hack: Find all elements with `bg-primary` and `text-primary`? Too slow.
            // Better: Inject a style tag that overrides the HEX color? 
            // Tailwind generates classes like `.bg-primary { background-color: ... }`
            // We can inject: 
            // <style id="branding-style"> .bg-primary { background-color: ${col} !important; } .text-primary { color: ${col} !important; } .border-primary { border-color: ${col} !important; } </style>

            let style = document.getElementById('branding-style');
            if (!style) {
                style = document.createElement('style');
                style.id = 'branding-style';
                document.head.appendChild(style);
            }
            style.innerHTML = `
                .bg-primary { background-color: ${config.primaryColor} !important; }
                .text-primary { color: ${config.primaryColor} !important; }
                .border-primary { border-color: ${config.primaryColor} !important; }
                .hover\\:bg-primary:hover { background-color: ${config.primaryColor} !important; }
                .hover\\:text-primary:hover { color: ${config.primaryColor} !important; }
                .hover\\:border-primary:hover { border-color: ${config.primaryColor} !important; }
            `;
        }

        // 2. Content Updates (Text, Logo, Meta)
        const updateContent = () => {
            // Text
            if (config.bankName) {
                document.title = `${config.bankName} | Secure Access`;
                document.querySelectorAll('.brand-text').forEach(el => el.textContent = config.bankName);
            }

            // Logo
            if (config.logoUrl) {
                document.querySelectorAll('.brand-logo-container').forEach(container => {
                    // Check if already has image to avoid flicker
                    if (container.querySelector('img.brand-logo-img')) {
                        container.querySelector('img.brand-logo-img').src = config.logoUrl;
                    } else {
                        // Clear icon, insert image
                        container.innerHTML = `<img src="${config.logoUrl}" alt="Logo" class="brand-logo-img w-full h-full object-contain">`;
                        container.classList.remove('bg-primary', 'p-2', 'text-white', 'p-1.5', 'p-1'); // Remove default icon styling
                        container.classList.add('w-12', 'h-12', 'flex', 'items-center', 'justify-center'); // Enforce size
                    }
                });
            }

            // Favicon
            if (config.faviconUrl) {
                let link = document.querySelector("link[rel~='icon']");
                if (!link) {
                    link = document.createElement('link');
                    link.rel = 'icon';
                    document.head.appendChild(link);
                }
                link.href = config.faviconUrl;
            }

            // Meta Image
            if (config.metaUrl) {
                let meta = document.querySelector('meta[property="og:image"]');
                if (!meta) {
                    meta = document.createElement('meta');
                    meta.setAttribute('property', 'og:image');
                    document.head.appendChild(meta);
                }
                meta.content = config.metaUrl;
            }

            // Copyright Year
            const year = new Date().getFullYear();
            document.querySelectorAll('.current-year').forEach(el => el.textContent = year);
        };

        updateContent();
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', updateContent);
        }
    },

    // --- Auth & User Management ---
    login: async (username, password) => {
        // For simulation, we are just querying the 'users' table directly 
        // since we didn't implement full Supabase Auth (simpler migration)
        const { data, error } = await supabaseClient
            .from('users')
            .select('*')
            .eq('username', username)
            .eq('password', password) // In real app, verify hash
            .single();

        if (error || !data) return null;

        // Store session locally for persistence across pages
        sessionStorage.setItem('currentUser', JSON.stringify(data));
        return data;
    },

    getCurrentUser: () => {
        const user = sessionStorage.getItem('currentUser');
        return user ? JSON.parse(user) : null;
    },

    logout: () => {
        sessionStorage.removeItem('currentUser');
        window.location.href = 'login.html';
    },

    // --- Data Formatting ---
    formatCurrency: (amount) => {
        return new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: 'USD'
        }).format(amount);
    },

    generateId: () => crypto.randomUUID(), // Use native UUID

    // --- Async Data Access ---

    // Get full user data (with balance and extra balances from settings)
    getUserData: async (userId) => {
        // Parallel Fetch for Performance
        const userPromise = supabaseClient
            .from('users')
            .select('*')
            .eq('id', userId)
            .single();

        const keys = [`u_${userId}_sav`, `u_${userId}_inv`, `u_${userId}_sav_locked`];
        const settingsPromise = supabaseClient
            .from('settings')
            .select('*')
            .in('key', keys);

        const [userResult, settingsResult] = await Promise.all([userPromise, settingsPromise]);

        const user = userResult.data;
        const userError = userResult.error;
        const settings = settingsResult.data;

        if (userError || !user) return null;

        // 3. Merge
        user.savings_balance = 0;
        user.investment_balance = 0;
        user.is_savings_locked = true;

        if (settings) {
            settings.forEach(item => {
                if (item.key === `u_${userId}_sav`) user.savings_balance = parseFloat(item.value);
                if (item.key === `u_${userId}_inv`) user.investment_balance = parseFloat(item.value);
                if (item.key === `u_${userId}_sav_locked`) user.is_savings_locked = item.value === 'true';
            });
        }

        return user;
    },

    verifyPin: async (userId, pin) => {
        const { data, error } = await supabaseClient
            .from('users')
            .select('pin')
            .eq('id', userId)
            .single();

        if (error || !data) return false;
        return data.pin === pin;
    },

    // Get transactions for a user
    getTransactions: async (userId) => {
        const { data, error } = await supabaseClient
            .from('transactions')
            .select('*')
            .eq('user_id', userId)
            .order('created_at', { ascending: false });
        return data || [];
    },

    // Create a transaction
    createTransaction: async (userId, amount, type, description, status = 'completed') => {
        // DB Constraint Workaround: Map custom types to 'debit'/'credit'
        let dbType = type;
        let dbDesc = description;

        if (type === 'investment_withdrawal') {
            dbType = 'debit'; // Logic is handled below, DB sees debit
            dbDesc = '[INV_WITHDRAWAL] ' + description;
        } else if (type === 'investment_deposit') {
            dbType = 'credit';
            dbDesc = '[INV_DEPOSIT] ' + description;
        }

        // 1. Insert Transaction
        const { error: txError } = await supabaseClient
            .from('transactions')
            .insert({
                user_id: userId,
                amount: amount,
                type: dbType,
                description: dbDesc || 'TRANSACTION',
                status: status
            });

        if (txError) throw txError;

        // 2. Update Balances (Router Logic)
        const user = await utils.getUserData(userId);

        // A. Standard Debit/Credit (Main Balance)
        if (type === 'debit' || (type === 'credit' && status === 'completed')) {
            let newBalance = Number(user.balance);
            if (type === 'debit') newBalance -= amount;
            else newBalance += amount;

            await utils.updateUser(userId, { balance: newBalance });
        }

        // B. Investment Withdrawal (Inv Balance)
        else if (type === 'investment_withdrawal') {
            // Deduct from investment balance (KV Store)
            let newInv = Number(user.investment_balance || 0);
            newInv -= amount;
            await utils.updateUser(userId, { investment_balance: newInv });
        }
        // C. Investment Deposit (Inv Balance)
        else if (type === 'investment_deposit') {
            let newInv = Number(user.investment_balance || 0);
            newInv += amount;
            await utils.updateUser(userId, { investment_balance: newInv });
        }
    },

    updateTransactionStatus: async (txId, newStatus) => {
        // 1. Get Transaction Details first
        const { data: tx, error: fetchError } = await supabaseClient
            .from('transactions')
            .select('*')
            .eq('id', txId)
            .single();

        if (fetchError || !tx) throw new Error('Transaction not found');
        if (tx.status === newStatus) return; // No change

        // 2. Handle Balance Reversal/Application
        // Logic:
        // - PENDING -> REJECTED (Debit): Refund money (Add balance).
        // - PENDING -> COMPLETED (Credit): Add money (Add balance). (Debit is already deducted on create)
        // - REJECTED -> PENDING/COMPLETED: Re-deduct? (Complex, let's keep it simple: Only handle Pending -> X)

        const user = await utils.getUserData(tx.user_id);
        let newBalance = Number(user.balance);
        let balanceChanged = false;

        if (tx.status === 'pending') {
            if (newStatus === 'rejected' && tx.type === 'debit') {
                // Refund the reserved funds
                newBalance += Number(tx.amount);
                balanceChanged = true;
            } else if (newStatus === 'completed' && tx.type === 'credit') {
                // Approve a deposit
                newBalance += Number(tx.amount);
                balanceChanged = true;
            }
        }

        // 3. Update Balance if needed
        if (balanceChanged) {
            const { error: balError } = await supabaseClient
                .from('users')
                .update({ balance: newBalance })
                .eq('id', tx.user_id);
            if (balError) throw balError;
        }

        // 4. Update Transaction Status
        const { error: updateError } = await supabaseClient
            .from('transactions')
            .update({ status: newStatus })
            .eq('id', txId);

        if (updateError) throw updateError;
    },

    // --- Admin Functions ---
    getAllUsers: async () => {
        const { data } = await supabaseClient.from('users').select('*').order('name');
        return data || [];
    },

    getAllTransactions: async () => {
        // Join with users to get names (Supabase syntax)
        const { data } = await supabaseClient
            .from('transactions')
            .select(`
                *,
                users (name)
            `)
            .order('created_at', { ascending: false });

        // Flatten structure for easier UI consumption: t.users.name -> t.userName
        return data.map(t => ({ ...t, userName: t.users?.name || 'Unknown' }));
    },

    updateTransaction: async (txId, updates) => {
        // 1. Fetch original transaction
        const { data: oldTx, error: fetchError } = await supabaseClient
            .from('transactions')
            .select('*')
            .eq('id', txId)
            .single();

        if (fetchError || !oldTx) throw new Error("Transaction not found");

        const user = await utils.getUserData(oldTx.user_id);
        let newBalance = Number(user.balance);
        let balanceChanged = false;

        // 2. Logic to reverse old impact and apply new impact (if status/amount changed)
        // Only impacts balance if status was/is 'completed' or 'pending' (for Debits).
        // Let's simplify: 
        // A DEBIT reduces balance if Pending OR Completed.
        // A CREDIT increases balance ONLY if Completed.

        const getImpact = (tx) => {
            if (tx.type === 'debit') {
                if (tx.status === 'completed' || tx.status === 'pending') return -Number(tx.amount);
            } else { // credit
                if (tx.status === 'completed') return Number(tx.amount);
            }
            return 0;
        };

        // Construct "New" transaction object (merging updates)
        const newTx = { ...oldTx, ...updates };

        const oldImpact = getImpact(oldTx);
        const newImpact = getImpact(newTx);

        if (oldImpact !== newImpact) {
            // Reverse old, Apply new
            newBalance = newBalance - oldImpact + newImpact;
            balanceChanged = true;
        }

        // 3. Update Balance
        if (balanceChanged) {
            const { error: balError } = await supabaseClient
                .from('users')
                .update({ balance: newBalance })
                .eq('id', oldTx.user_id);
            if (balError) throw balError;
        }

        // 4. Update Transaction
        const { error } = await supabaseClient
            .from('transactions')
            .update(updates)
            .eq('id', txId);
        if (error) throw error;
    },

    createUser: async (userData) => {
        // Ensure PIN falls back to defaults if not provided, though DB default handles it too
        const { error } = await supabaseClient.from('users').insert(userData);
        if (error) throw error;
    },

    updateUser: async (id, updates) => {
        // Split updates into Core (DB) and Extra (Settings KV)
        const coreFields = ['name', 'username', 'password', 'pin', 'balance', 'is_admin'];
        const coreUpdates = {};
        const settingsUpserts = [];

        Object.keys(updates).forEach(key => {
            if (coreFields.includes(key)) {
                coreUpdates[key] = updates[key];
            } else {
                // Map to settings keys
                let settingKey = null;
                if (key === 'savings_balance') settingKey = `u_${id}_sav`;
                if (key === 'investment_balance') settingKey = `u_${id}_inv`;
                if (key === 'is_savings_locked') settingKey = `u_${id}_sav_locked`;

                if (settingKey) {
                    settingsUpserts.push({ key: settingKey, value: String(updates[key]) });
                }
            }
        });

        // Parallel Execution
        const promises = [];

        // 1. Update Core
        if (Object.keys(coreUpdates).length > 0) {
            promises.push(
                supabaseClient.from('users').update(coreUpdates).eq('id', id).then(({ error }) => { if (error) throw error; })
            );
        }

        // 2. Update Settings
        if (settingsUpserts.length > 0) {
            promises.push(
                supabaseClient.from('settings').upsert(settingsUpserts, { onConflict: 'key' }).then(({ error }) => { if (error) throw error; })
            );
        }

        await Promise.all(promises);
    },

    deleteUser: async (id) => {
        // Cascade delete transactions first usually, or relay on DB cascade
        await supabaseClient.from('transactions').delete().eq('user_id', id);
        const { error } = await supabaseClient.from('users').delete().eq('id', id);
        if (error) throw error;
    },
    deleteTransaction: async (txId) => {
        // 1. Fetch original to reverse balance
        const { data: originalTx, error: fetchError } = await supabaseClient
            .from('transactions')
            .select('*')
            .eq('id', txId)
            .single();

        if (fetchError || !originalTx) throw new Error('Transaction not found');

        // 2. Reverse Balance Impact
        if (originalTx.status === 'completed') {
            const negation = originalTx.type === 'credit' ? -originalTx.amount : originalTx.amount;

            // Apply negation
            const { error: balanceError } = await supabaseClient.rpc('increment_balance', {
                user_id: originalTx.user_id,
                amount: negation
            });

            if (balanceError) {
                // Fallback if RPC fails or doesn't exist (simulated approach)
                const { data: user } = await supabaseClient.from('users').select('balance').eq('id', originalTx.user_id).single();
                if (user) {
                    await supabaseClient.from('users').update({ balance: user.balance + negation }).eq('id', originalTx.user_id);
                }
            }
        }

        // 3. Delete Record
        const { error: deleteError } = await supabaseClient
            .from('transactions')
            .delete()
            .eq('id', txId);

        if (deleteError) throw deleteError;
        return true;
    }
};
